#!/bin/bash
# Install the desktop shell on macOS and build a double-clickable app bundle.
#
# Idempotent: picks a stable CPython >= 3.11, rebuilds .venv only when it is
# on a different interpreter, installs the project with the desktop extra,
# verifies pywebview imports, and (re)writes ~/Applications/<name>.app whose
# launcher runs `python -m vaspilot desktop` from the repository.
#
# Usage:  scripts/install-desktop.sh [/path/to/python3]
set -euo pipefail

repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
venv="$repo/.venv"
app_name="远端控制智能体"
bundle="$HOME/Applications/$app_name.app"
icon_src="$repo/src/vaspilot/desktop/assets/icon.icns"

if [[ $(uname -s) != Darwin ]]; then
    echo "This installer is for macOS; on Windows run scripts\\install-desktop.ps1" >&2
    exit 1
fi

# -- 1. interpreter -----------------------------------------------------------
stable_python() {
    local exe=$1
    [[ -x $exe || $(command -v "$exe" 2>/dev/null) ]] || return 1
    "$exe" -c 'import sys; v=sys.version_info; \
               raise SystemExit(0 if v[:2] >= (3, 11) and v.releaselevel == "final" else 1)' \
        2>/dev/null || return 1
    return 0
}

python_exe=""
for candidate in "${1:-}" python3.13 python3.12 python3.11 python3; do
    [[ -n $candidate ]] || continue
    if stable_python "$candidate"; then
        python_exe=$(command -v "$candidate" 2>/dev/null || echo "$candidate")
        break
    fi
done
if [[ -z $python_exe ]]; then
    echo "No stable CPython >= 3.11 found. Pass one: scripts/install-desktop.sh /path/to/python3" >&2
    exit 1
fi
version=$("$python_exe" -c 'import sys; print("%d.%d.%d" % sys.version_info[:3])')
echo "Interpreter: $python_exe ($version)"

# -- 2. virtual environment ---------------------------------------------------
rebuild=1
if [[ -f $venv/pyvenv.cfg ]]; then
    have=$(awk -F'= *' '/^version/ {print $2}' "$venv/pyvenv.cfg" | tr -d ' ')
    [[ $have == "$version" ]] && rebuild=0
fi
if (( rebuild )); then
    [[ -d $venv ]] && { echo "Removing .venv (different interpreter)"; rm -rf "$venv"; }
    echo "Creating .venv"
    "$python_exe" -m venv "$venv"
else
    echo ".venv already on $version; keeping it"
fi

venv_py="$venv/bin/python"
echo "Installing project with desktop + dev extras"
"$venv_py" -m pip install --disable-pip-version-check -e "$repo[desktop,dev]"
"$venv_py" -c 'import importlib.metadata as m, webview; print("pywebview", m.version("pywebview"))'

# -- 3. icon ------------------------------------------------------------------
[[ -f $icon_src ]] || "$venv_py" "$repo/scripts/make_icon.py"
[[ -f $icon_src ]] || { echo "icon missing: $icon_src" >&2; exit 1; }

# -- 4. app bundle ------------------------------------------------------------
mkdir -p "$bundle/Contents/MacOS" "$bundle/Contents/Resources"
cp "$icon_src" "$bundle/Contents/Resources/icon.icns"

cat > "$bundle/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>$app_name</string>
    <key>CFBundleDisplayName</key>     <string>$app_name</string>
    <key>CFBundleIdentifier</key>      <string>local.vaspilot.desktop</string>
    <key>CFBundleVersion</key>         <string>1.0</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>CFBundleExecutable</key>      <string>launcher</string>
    <key>CFBundleIconFile</key>        <string>icon</string>
    <key>NSHighResolutionCapable</key> <true/>
</dict>
</plist>
PLIST

cat > "$bundle/Contents/MacOS/launcher" <<LAUNCHER
#!/bin/bash
# Generated by scripts/install-desktop.sh — re-run it after moving the repo.
cd "$repo"
exec "$venv_py" -m vaspilot desktop
LAUNCHER
chmod +x "$bundle/Contents/MacOS/launcher"
touch "$bundle"   # nudge Finder to re-read the icon

echo "App bundle: $bundle"
echo "Done. Open it from Launchpad or ~/Applications."
